# Data Notebook
-----
This note book is being used to; Investigate a dataset, and provide recommendations or insights based on the available data.
Goals:
- Data Cleaning
- Visualisation

For extensive list of goals, check ```README.md```

## Index:

## Importing Libraries and Dataset selection
-----

### Importing:
-----

In [2]:
# Start
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Dataset:
-----

In [20]:
# Defining dataset
sol = sns.load_dataset('planets')
sol.head() # Test dataset is loaded

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

## Initial Data Exploration
-----
### Tasks:
- Number of rows and columns
- Column names
- Data types
- Further possible exploration

### Number of rows and columns

In [22]:
# Number of rows and columns (standard)
sol

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [26]:
# Number of rows and columns (numpy)
sol.info()

<class 'pandas.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   str
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), str(1)
memory usage: 48.6 KB

## Data Cleaning
-----
### Tasks:
1. Identify and remove Duplicates
2. Locate Data with Missing values
3. Data type conversion, convert Data Types where needed.

In [30]:
# Duplicates

In [27]:
# Missing values

In [29]:
# Data type conversion

## Data analysis
-----
### Task:
1. Develop at least 5 analytical questions
2. Use Pandas to answer those questions

In [31]:
# Question 1:

In [32]:
# Question 2:

In [33]:
# Question 3:

In [ ]:
# Question 4:

In [35]:
# Question 5:

## Visualistions
-----
### Tasks:
1. Create visualisations to support/provide evidence for you findings
2. Each chart should answer a question
3. Each should support a conclusion or recommendation